# Just for clarity and not required to be set since default port is '8080'.
server:
  port: 8080

# Register self as a client to service-registry.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Must match the name of the configuration files managed by config-server (this includes profile specific configuration files).
spring:
  application:
    name: api-gateway

# Defaults to 'http://localhost:8888' if discovery is not enabled otherwise use entries from service-registry.
  config:
    import: 'optional:configserver:'

# Use service-registry to find other config-server instances so that URL does not have to be set in 'spring.config.import'.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

# Routes    
    gateway:
      routes:
      - id: booking-app-route
        uri: http://localhost:9080/
        predicates:
        - Path=/booking/**
        - Method=GET,POST,PUT,DELETE
        filters:
        - AddRequestHeader=X-Request-Color, red
        - AddResponseHeader=X-Response-Color, blue